### ISSUE TITLE
Question: how to query translated data

### ISSUE THREAD

**Issue by freekmurze** [themsaid/laravel-multilingual#1]
It's very neat that the translations are stored in a json column. What is the easiest way to query translated data? For example: if name is a translatable attribute how can I find a record with a certain name for a certain language?

**Comment by themsaid** [comment]
Currently I simply do `->where('name', 'LIKE', "%$input%")`. Maybe this is not the best way to do it, but it was enough for the cases I've been through so far.

**Comment by freekmurze** [comment]
That'll work but it's not fine grained enough when you want to lookup things like slugs. I'm hoping Laravel will add some Collection methods soon to help you in querying translated data in a more exact way.

**Comment by mohamedsharaf** [comment]
i fell happy i landed here :) but one thing i know mysql support index to json only through virtual clone

but its done based on the key 
how we can add index based on the value 

like @freekmurze example add index for name search
