### ISSUE TITLE
utf-8 data are saved as json escaped

### ISSUE THREAD

**Issue by mbouclas** [themsaid/laravel-multilingual#3]
So the thing is that when your translatable field is of type text (cause your mysql doesn' support json format) and you save it what you get is escaped json like so
```
{"en":"\u039d\u03ad\u03b1"}
```

which is pretty much useless. The solution of course is to json_encode with the JSON_UNESCAPED_UNICODE flag. Is that possible?

**Comment by themsaid** [comment]
Thank you for your feedback on this, however saving the language values is done via laravel, which doesn't use this flag `JSON_UNESCAPED_UNICODE `, you can however use your own `setNameAttribute` mutator and use the flag as you please.

**Comment by mbouclas** [comment]
I thought as much. Was just wondering if you happened to stumble upon this problem and maybe had a more elegant solution.

Thanks

**Comment by themsaid** [comment]
I use mutators to get around that, maybe the way JSON is encoded in laravel need to be altered to unescape unicode characters, need to study the effect of that on how laravel works before attempting to submit a PR though :)

**Comment by mbouclas** [comment]
I solved the ugly mutators issue by creating a trait which overrides the default implementation

```
trait JsonAsUtf8
{
    /**
     * @param $value
     * @return string
     */
    protected function asJson($value)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
}
```

and then in the model i use it along side your trait

```
class Test extends Model
{
    use Translatable, JsonAsUtf8;

}
```

Could be far more elegant if this trait was a part of the translatable trait. What do you think?

**Comment by themsaid** [comment]
Yeah I think so, it'd be great if you could PR such thing :)

**Comment by mbouclas** [comment]
I submitted a PR

**Comment by themsaid** [comment]
Merged, thanks :)
