### ISSUE TITLE
Translatable trait not found

### ISSUE THREAD

**Issue by macnux** [themsaid/laravel-multilingual#5]
after installing the package and adding the service provider to app/config

i have a country model which has a name field that needs to be translatable 

```
class Country extends Model {

 use Themsaid\Multilingual\Translatable;  <==== use the trait as requested inside the class

    protected $table = 'countries';

    public $translatable = ['name'];
    public $casts = ['name' => 'array'];

}
```

then i run this simple code

```
$c=Country::where('id',275)->first();
    dd($c->name);
```

it gave me this error

`Trait 'App\Models\Main\Themsaid\Multilingual\Translatable' not found`

note:when i put the trait line outside the class it works but it returns the both values for the name !!
like this

```
array:2 [▼
  "en" => "Zulu"
  "nl" => "Zulñ"
]
```

what i expect from the package is to get only one value based on the current locale

**Comment by themsaid** [comment]
You need to load the trait from the global namespace;

```
\Themsaid\Multilingual\Translatable
```

instead of:

```
Themsaid\Multilingual\Translatable
```

**Comment by macnux** [comment]
oh thanks.. did not see it
