### ISSUE TITLE
Proposal:updating specific locale text instead of all locales

### ISSUE THREAD

**Issue by macnux** [themsaid/laravel-multilingual#6]
the package is reallly handy and helpful but will be more handy if:

instead of updating all locales you can make update goes for specific local
ex.

```
Country::find($id)->update([
    'name' => [
        'nl' => "Yumô"
    ]
]);
```

this above code clear the name field with its previous input ad put the new text
so can you update the existing text by **appending** the new local if it does not exists to the existing one

**Comment by jrmadsen67** [comment]
the appending part is something I'll need to look at more closely later, but right now use this syntax to update one at a time:

    Country::find($id)->update(['name->nl' => 'Yumô']);

**Comment by themsaid** [comment]
Sorry no plans to deal with this inside the package :) Laravel has a very nice API for dealing with JSON columns.
