### ISSUE TITLE
get text specific locale from eloquent joins 

### ISSUE THREAD

**Issue by macnux** [themsaid/laravel-multilingual#7]
im using eloquent joins to get some data like this

```
 $areas = Area::leftJoin('provinces','areas.zone_id','=','provinces.id')
        ->leftJoin('countries','provinces.country_id','=','countries.id')
        ->select(['areas.id AS aid', 'countries.name AS cname', 'provinces.name AS pname','areas.name AS aname','areas.code AS acode','areas.zip_code' ]);
```

now how i can get the country name in a specific locale in the above code

i try also direct queries and did not work

`$c=Country::where('name->en','=','Egypt')->first();`
`$c=Country::whereRaw('name->en="Egypt"')->first();`

both gives me Syntax error

**Comment by macnux** [comment]
im using mysql 5.6 
when i try mysql 5.7 and make a json field and put the json string on it it works
now..

can i achieve the same behavior on mysql 5.6 which does not have json field but using text field?

**Comment by mbouclas** [comment]
I don't think you can. In 5.6 you don't have the javascript engine to run queries like `name->en="Egypt"` so it won't work.

**Comment by jrmadsen67** [comment]
It *will* work for selecting; for create/update you need to build the fields into an array & let Laravel transform to a json string. I'm working on some functions to help with this
